# Generated by Django 3.2.16 on 2022-12-25 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_blogger_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
    ]
