# Generated by Django 3.2.16 on 2022-12-20 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
        ('place', '0010_service_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='place.guide')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='facility.hotel')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='facility.food')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='place.place')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='place.service')),
            ],
        ),
    ]
