# Generated by Django 3.2.16 on 2022-12-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_service_guide'),
        ('travel', '0002_trip_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='service',
        ),
        migrations.AddField(
            model_name='trip',
            name='service',
            field=models.ManyToManyField(related_name='trips', to='place.Service'),
        ),
    ]
