# Generated by Django 3.2.16 on 2023-01-01 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_alter_image_image'),
        ('travel', '0003_auto_20221220_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='place.guide'),
        ),
    ]
