# Generated by Django 3.2.16 on 2023-01-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20230103_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='multiple', max_length=150),
        ),
    ]
