# Generated by Django 3.2.16 on 2023-01-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20230103_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_type',
            new_name='type',
        ),
    ]
