# Generated by Django 3.2.16 on 2023-01-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_rename_group_type_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
