# Generated by Django 3.2.16 on 2023-01-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_trip_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='members',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='type',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple'), ('family', 'Family group')], default='multiple', max_length=150),
        ),
    ]
