# Generated by Django 3.2.16 on 2023-01-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_auto_20230108_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple'), ('family', 'Family group')], default='multiple', max_length=150),
        ),
    ]
