# Generated by Django 3.2.16 on 2023-02-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_alter_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
