# Generated by Django 3.2.16 on 2022-12-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_alter_place_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='map',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
