# Generated by Django 3.2.16 on 2022-12-19 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('country', '0002_country_currency'),
        ('place', '0004_alter_place_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('experience', models.TextField()),
                ('language', models.ManyToManyField(related_name='guides', to='country.Language')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='place.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
