# Generated by Django 3.2.16 on 2022-12-20 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_alter_guide_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
