# Generated by Django 3.2.16 on 2022-12-20 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_guide_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='guide',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='place.guide'),
            preserve_default=False,
        ),
    ]
