# Generated by Django 3.2.16 on 2022-12-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_service_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places', verbose_name='pictures'),
        ),
    ]
