# Generated by Django 3.2.16 on 2023-01-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
